name: test-with-catch2
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: g++ src/test_main.cpp tests/catch_amalgamated -o src/test_main
      - run: ./src/test_main # run tests
